# -*- coding: utf-8 -*-

# fmt: off
ENV_VAR_NAME_FOR_AWS_PROFILE_FOR_CDK = "AWS_PROFILE_FOR_CDK"
TEST_IAM_USER_NAME = "project-boto_session_manager"
TEST_IAM_ROLE_NAME = "project-boto_session_manager"
GITHUB_ENV_VAR_NAME_FOR_AWS_ACCESS_KEY_ID_FOR_GITHUB_CI = "AWS_ACCESS_KEY_ID_FOR_GITHUB_CI"
GITHUB_ENV_VAR_NAME_FOR_AWS_SECRET_ACCESS_KEY_FOR_GITHUB_CI = "AWS_SECRET_ACCESS_KEY_FOR_GITHUB_CI"
# fmt: on
